spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/maomao_mall_goods
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'a19932909'
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
